-- SQL Script to create the 'consultations' table in Supabase SQL Editor

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.consultations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT NOT NULL,
    service TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS) - Optional but recommended by Supabase
ALTER TABLE public.consultations ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow all actions for service_role / authenticated admin
CREATE POLICY "Allow full access to service_role" 
ON public.consultations 
TO service_role 
USING (true) 
WITH CHECK (true);

-- 4. Create a policy to allow inserts (bookings) for anyone (public/anon)
CREATE POLICY "Allow public inserts" 
ON public.consultations 
FOR INSERT 
TO anon, authenticated
WITH CHECK (true);

-- 5. Create a policy to allow select/delete for authenticated admin users
CREATE POLICY "Allow authenticated read/write access" 
ON public.consultations 
TO authenticated 
USING (true) 
WITH CHECK (true);
