-- SQL Script to create the 'collections' table in Supabase SQL Editor

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT NOT NULL,
    category TEXT NOT NULL,
    image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow all actions for service_role (used by Express backend server role)
CREATE POLICY "Allow full access to service_role" 
ON public.collections 
TO service_role 
USING (true) 
WITH CHECK (true);

-- 4. Create a policy to allow public read access (select) for everyone (anon and authenticated)
CREATE POLICY "Allow public read access" 
ON public.collections 
FOR SELECT 
TO anon, authenticated
USING (true);

-- 5. Create a policy to allow read/write access for authenticated admin users
CREATE POLICY "Allow authenticated read/write access" 
ON public.collections 
TO authenticated 
USING (true) 
WITH CHECK (true);
